import { Router } from 'express';
import type { ResultSetHeader, RowDataPacket } from 'mysql2';
import { z } from 'zod';
import { requireAuth, requireRoles } from '../../auth/middleware.js';
import { writeAuditLog } from '../../db/audit.js';
import { pool } from '../../db/pool.js';
import { asyncHandler } from '../../http/async-handler.js';
import { AppError } from '../../http/errors.js';

export const shiftRouter=Router();
shiftRouter.use(requireAuth,requireRoles('SUPER_ADMIN','HR_MANAGER'));
const time=z.string().regex(/^([01]\d|2[0-3]):[0-5]\d$/,'Giờ phải có dạng HH:mm');
const shiftSchema=z.object({shiftCode:z.string().trim().min(1).max(30),shiftName:z.string().trim().min(2).max(120),startTime:time,endTime:time,breakMinutes:z.number().int().min(0).max(300).default(60),lateGraceMinutes:z.number().int().min(0).max(180).default(10),earlyLeaveGraceMinutes:z.number().int().min(0).max(180).default(10),standardWorkMinutes:z.number().int().positive().max(1440),isOvernight:z.boolean().default(false),isActive:z.boolean().default(true)});

shiftRouter.get('/',asyncHandler(async(_req,res)=>{const [rows]=await pool.query<RowDataPacket[]>(`SELECT shift_id shiftId,shift_code shiftCode,shift_name shiftName,TIME_FORMAT(start_time,'%H:%i') startTime,TIME_FORMAT(end_time,'%H:%i') endTime,break_minutes breakMinutes,late_grace_minutes lateGraceMinutes,early_leave_grace_minutes earlyLeaveGraceMinutes,standard_work_minutes standardWorkMinutes,is_overnight isOvernight,is_active isActive FROM shifts ORDER BY is_active DESC,start_time,shift_id`);res.json({success:true,data:rows});}));
shiftRouter.post('/',asyncHandler(async(req,res)=>{const body=shiftSchema.parse(req.body);const connection=await pool.getConnection();try{await connection.beginTransaction();const [result]=await connection.execute<ResultSetHeader>(`INSERT INTO shifts(shift_code,shift_name,start_time,end_time,break_minutes,late_grace_minutes,early_leave_grace_minutes,standard_work_minutes,is_overnight,is_active) VALUES(?,?,?,?,?,?,?,?,?,?)`,[body.shiftCode,body.shiftName,body.startTime,body.endTime,body.breakMinutes,body.lateGraceMinutes,body.earlyLeaveGraceMinutes,body.standardWorkMinutes,body.isOvernight,body.isActive]);await writeAuditLog(connection,{action:'SHIFT_CREATED',entityType:'SHIFT',entityId:result.insertId,after:body,ipAddress:req.ip,userAgent:req.get('user-agent')});await connection.commit();res.status(201).json({success:true,data:{shiftId:result.insertId}});}catch(error){await connection.rollback();throw error;}finally{connection.release();}}));
shiftRouter.put('/:shiftId',asyncHandler(async(req,res)=>{const {shiftId}=z.object({shiftId:z.coerce.number().int().positive()}).parse(req.params);const body=shiftSchema.parse(req.body);const connection=await pool.getConnection();try{await connection.beginTransaction();const [before]=await connection.query<RowDataPacket[]>('SELECT * FROM shifts WHERE shift_id=? LIMIT 1 FOR UPDATE',[shiftId]);if(!before[0])throw new AppError(404,'Không tìm thấy ca làm','SHIFT_NOT_FOUND');await connection.execute(`UPDATE shifts SET shift_code=?,shift_name=?,start_time=?,end_time=?,break_minutes=?,late_grace_minutes=?,early_leave_grace_minutes=?,standard_work_minutes=?,is_overnight=?,is_active=? WHERE shift_id=?`,[body.shiftCode,body.shiftName,body.startTime,body.endTime,body.breakMinutes,body.lateGraceMinutes,body.earlyLeaveGraceMinutes,body.standardWorkMinutes,body.isOvernight,body.isActive,shiftId]);await writeAuditLog(connection,{action:'SHIFT_UPDATED',entityType:'SHIFT',entityId:shiftId,before:before[0],after:body,ipAddress:req.ip,userAgent:req.get('user-agent')});await connection.commit();res.json({success:true,data:{shiftId}});}catch(error){await connection.rollback();throw error;}finally{connection.release();}}));
